// Shared subtitle styles - used by both landing showcase and editor
// No backend mention - pure UI definitions

export const SUBTITLE_STYLES = {
  hormozi: {
    id: 'hormozi',
    name: 'Hormozi',
    desc: 'Bold yellow highlight viral',
    preview: 'RAHASIA JADI KAYA',
    font: 'Anton',
    fontClass: 'font-black tracking-tight',
    textColor: '#FFFFFF',
    highlightColor: '#FFD60A',
    strokeColor: '#000000',
    strokeWidth: 8,
    bgColor: 'transparent',
    bgClass: 'bg-transparent',
    textClass: 'text-white',
    highlightClass: 'bg-[#FFD60A] text-black px-1.5 py-0.5 rounded',
    strokeClass: 'drop-shadow-[0_2px_0_rgba(0,0,0,1)]',
    upper: true,
    usage: '67%',
    bgPreview: '#0A0A0A',
  },
  mrbeast: {
    id: 'mrbeast',
    name: 'MrBeast',
    desc: 'Big bold energetic red',
    preview: 'INSANE GILA BANGET',
    font: 'Bebas Neue',
    fontClass: 'font-black',
    textColor: '#FFFFFF',
    highlightColor: '#FF2D2D',
    strokeColor: '#000000',
    strokeWidth: 10,
    bgColor: 'transparent',
    bgClass: 'bg-transparent',
    textClass: 'text-white',
    highlightClass: 'text-[#FF2D2D]',
    strokeClass: 'drop-shadow-[0_3px_0_rgba(0,0,0,1)]',
    upper: true,
    usage: '23%',
    bgPreview: '#1A1A1A',
  },
  karaoke: {
    id: 'karaoke',
    name: 'Karaoke',
    desc: 'Box highlight word by word',
    preview: 'Karaoke style highlight',
    font: 'Montserrat',
    fontClass: 'font-bold',
    textColor: '#0A0A0A',
    highlightColor: '#FFFFFF',
    strokeColor: 'transparent',
    strokeWidth: 0,
    bgColor: '#FFD60A',
    bgClass: 'bg-[#FFD60A]',
    textClass: 'text-black',
    highlightClass: 'bg-[#FFD60A] text-black',
    strokeClass: '',
    upper: false,
    usage: '18%',
    bgPreview: '#FFD60A',
  },
  minimal: {
    id: 'minimal',
    name: 'Minimal',
    desc: 'Clean professional white',
    preview: 'Clean and simple',
    font: 'Inter',
    fontClass: 'font-medium',
    textColor: '#0A0A0A',
    highlightColor: '#0A0A0A',
    strokeColor: '#FFFFFF',
    strokeWidth: 0,
    bgColor: 'rgba(255,255,255,0.9)',
    bgClass: 'bg-white/90',
    textClass: 'text-[#0A0A0A]',
    highlightClass: 'underline decoration-2 underline-offset-4',
    strokeClass: 'drop-shadow-[0_1px_2px_rgba(0,0,0,0.1)]',
    upper: false,
    usage: '12%',
    bgPreview: '#F5F5F0',
  },
  tiktok: {
    id: 'tiktok',
    name: 'TikTok Viral',
    desc: '2 words center bold',
    preview: 'VIRAL BANGET',
    font: 'Oswald',
    fontClass: 'font-black',
    textColor: '#FFFFFF',
    highlightColor: '#FF2D55',
    strokeColor: '#000000',
    strokeWidth: 6,
    bgColor: 'transparent',
    bgClass: 'bg-transparent',
    textClass: 'text-white',
    highlightClass: 'text-[#FF2D55]',
    strokeClass: 'drop-shadow-[0_2px_0_rgba(0,0,0,1)]',
    upper: true,
    usage: '34%',
    bgPreview: '#000000',
  },
  editorial: {
    id: 'editorial',
    name: 'Editorial',
    desc: 'Serif premium elegant',
    preview: 'Premium Storytelling',
    font: 'Georgia',
    fontClass: 'font-serif font-bold',
    textColor: '#0A0A0A',
    highlightColor: '#0A0A0A',
    strokeColor: '#FFFFFF',
    strokeWidth: 4,
    bgColor: 'rgba(255,255,255,0.95)',
    bgClass: 'bg-white/95',
    textClass: 'text-[#0A0A0A]',
    highlightClass: 'bg-white/90',
    strokeClass: '',
    upper: false,
    usage: '9%',
    bgPreview: '#FFFFFF',
  },
  netflix: {
    id: 'netflix',
    name: 'Netflix',
    desc: 'Red cinematic bold',
    preview: 'CINEMA RED',
    font: 'Bebas Neue',
    fontClass: 'font-black tracking-wide',
    textColor: '#FFFFFF',
    highlightColor: '#E50914',
    strokeColor: '#000000',
    strokeWidth: 6,
    bgColor: 'transparent',
    bgClass: 'bg-transparent',
    textClass: 'text-white',
    highlightClass: 'text-[#E50914]',
    strokeClass: 'drop-shadow-[0_2px_0_rgba(0,0,0,1)]',
    upper: true,
    usage: '15%',
    bgPreview: '#000000',
  },
  youtube: {
    id: 'youtube',
    name: 'YouTube',
    desc: 'White bold clean modern',
    preview: 'YouTube Style',
    font: 'Inter',
    fontClass: 'font-bold',
    textColor: '#FFFFFF',
    highlightColor: '#FF0000',
    strokeColor: '#000000',
    strokeWidth: 5,
    bgColor: 'transparent',
    bgClass: 'bg-transparent',
    textClass: 'text-white',
    highlightClass: 'text-[#FF0000]',
    strokeClass: 'drop-shadow-[0_2px_4px_rgba(0,0,0,0.8)]',
    upper: false,
    usage: '28%',
    bgPreview: '#212121',
  },
  bold: {
    id: 'bold',
    name: 'Bold',
    desc: 'Extra bold white black stroke',
    preview: 'BOLD TEXT',
    font: 'Anton',
    fontClass: 'font-black',
    textColor: '#FFFFFF',
    highlightColor: '#FFFFFF',
    strokeColor: '#000000',
    strokeWidth: 9,
    bgColor: 'transparent',
    bgClass: 'bg-transparent',
    textClass: 'text-white',
    highlightClass: 'text-white',
    strokeClass: 'drop-shadow-[0_3px_0_rgba(0,0,0,1)]',
    upper: true,
    usage: '19%',
    bgPreview: '#0A0A0A',
  },
  glow: {
    id: 'glow',
    name: 'Glow',
    desc: 'Neon glow effect green',
    preview: 'GLOW NEON',
    font: 'Montserrat',
    fontClass: 'font-black',
    textColor: '#FFFFFF',
    highlightColor: '#00FF88',
    strokeColor: '#000000',
    strokeWidth: 4,
    bgColor: 'transparent',
    bgClass: 'bg-transparent',
    textClass: 'text-white',
    highlightClass: 'text-[#00FF88] drop-shadow-[0_0_8px_#00FF88]',
    strokeClass: 'drop-shadow-[0_0_10px_rgba(0,255,136,0.5)]',
    upper: true,
    usage: '11%',
    bgPreview: '#0A0A0A',
  },
  outline: {
    id: 'outline',
    name: 'Outline',
    desc: 'Outline only white',
    preview: 'OUTLINE ONLY',
    font: 'Bebas Neue',
    fontClass: 'font-black',
    textColor: 'transparent',
    highlightColor: '#FFFFFF',
    strokeColor: '#FFFFFF',
    strokeWidth: 3,
    bgColor: 'transparent',
    bgClass: 'bg-transparent',
    textClass: 'text-transparent',
    highlightClass: 'text-white',
    strokeClass: '[ -webkit-text-stroke:2px_white ]',
    upper: true,
    usage: '8%',
    bgPreview: '#000000',
  },
  shadow: {
    id: 'shadow',
    name: 'Shadow',
    desc: 'Soft shadow yellow',
    preview: 'Shadow Soft',
    font: 'Inter',
    fontClass: 'font-bold',
    textColor: '#FFFFFF',
    highlightColor: '#FFD60A',
    strokeColor: '#000000',
    strokeWidth: 0,
    bgColor: 'transparent',
    bgClass: 'bg-transparent',
    textClass: 'text-white',
    highlightClass: 'text-[#FFD60A]',
    strokeClass: 'drop-shadow-[2px_2px_8px_rgba(0,0,0,0.6)]',
    upper: false,
    usage: '13%',
    bgPreview: '#2A2A2A',
  },
} as const

export const SUBTITLE_ANIMATIONS = {
  pop: { id: 'pop', name: 'Pop', desc: 'Scale pop on word', usage: '45%' },
  bounce: { id: 'bounce', name: 'Bounce', desc: 'Bouncy energetic', usage: '22%' },
  slide: { id: 'slide', name: 'Slide', desc: 'Slide up smooth', usage: '15%' },
  fade: { id: 'fade', name: 'Fade', desc: 'Fade in elegant', usage: '8%' },
  karaoke: { id: 'karaoke', name: 'Karaoke', desc: 'Word by word box', usage: '18%' },
  wave: { id: 'wave', name: 'Wave', desc: 'Wave motion', usage: '11%' },
  typewriter: { id: 'typewriter', name: 'Typewriter', desc: 'Ketik per huruf', usage: '14%' },
  glitch: { id: 'glitch', name: 'Glitch', desc: 'Glitch effect', usage: '7%' },
  zoom: { id: 'zoom', name: 'Zoom', desc: 'Zoom in', usage: '12%' },
  rotate: { id: 'rotate', name: 'Rotate', desc: 'Rotate 3D', usage: '6%' },
} as const

export type SubtitleStyleId = keyof typeof SUBTITLE_STYLES
export type SubtitleAnimId = keyof typeof SUBTITLE_ANIMATIONS
